### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by rootwork** [sttk/ansi-colors-prioritized#1]
Not sure if this project is still active, but in [Usage](https://github.com/sttk/ansi-colors-prioritized#usage) the first line is:

```const prioritizedColor = require('ansi-color-prioritized');```

but should be:

```const prioritizedColor = require('ansi-colors-prioritized');```

(note `s` in package name).

**Comment by sttk** [comment]
@rootwork Thanks for your report! I'll modify it.

**Comment by sttk** [comment]
@rootwork I fixed this issue by pr #2, so I'll close this.

Thanks!
